In [2]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [5]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
weights_input_to_hidden

array([[ 0.07384666,  0.01713683, -0.01156483],
       [-0.03011037, -0.1478522 , -0.07198442],
       [-0.04606388,  0.10571222,  0.03436183],
       [-0.17630402,  0.0324084 , -0.03850823]])

In [9]:
# TODO: Make a forward pass through the network
hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_in

array([-0.25750746,  0.14678234, -0.03218496])

In [10]:
hidden_layer_out = sigmoid(hidden_layer_in)
hidden_layer_out

array([ 0.43597653,  0.53662984,  0.49195446])

In [11]:
print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[ 0.43597653  0.53662984  0.49195446]
Output-layer Output:
[ 0.49613223  0.51535294]
